my-armor:
  head:
    u: 90
    v: 0
    w: 0
    item:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND_HELMET
  chest:
    u: 90
    v: 0
    w: 0
    item:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND_CHESTPLATE
  arms:
    left:
      u: 90
      v: 0
      w: 0
    right:
      u: 90
      v: 0
      w: 0
    item:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND_SWORD
    drop_chance: 0.5
  legs:
    left:
      u: 90
      v: 0
      w: 0
    right:
      u: 90
      v: 0
      w: 0
    item:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND_LEGGINGS
    boots:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND_BOOTS